<?php
/**
 * Created by PhpStorm.
 * User: polyanin
 * Date: 09.08.2018
 * Time: 21:54
 */

namespace Aplab\AplabAdminBundle;


use Aplab\AplabAdminBundle\Util\UiDataTransmitter;
use Symfony\Component\HttpKernel\Bundle\Bundle;

class AplabAdminBundle extends Bundle
{
    public function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub
        $this->container->get('twig')->addGlobal(
            'UiDataTransmitter', new UiDataTransmitter
        );
    }
//
//    /**
//     * Overridden to allow for the custom extension alias.
//     */
//    public function getContainerExtension()
//    {
//        if (null === $this->extension) {
//            $this->extension = new AplabAdminBundleExtension;
//        }
//        return $this->extension;
//    }

}